FRONTENDSCHOOL10/Haemadi

- src/styles/_theme.css
feature/global_style-> develop 
- styles/_theme.css 색상 및 크기 설정
Resolves #11
> design: 공통 스타일 설정

- package.json
- pnpm-lock.yaml
- src/components/ModalDialog/ModalDialog.jsx
- src/components/ModalDialog/ModalDialog.module.css
- src/main.jsx
feature/ModalDialog -> develop
- react-modal 라이브러리 사용
- 제목과 내용을 children으로 입력받음
- contentLabel을 입력받으면 모달 창의 aria-label 속성으로 들어감
- min-width 640px를 기준으로 pc 스타일 적용 (모바일 first)
**모바일**
**PC**
Resolves #14
> feat: ModalDialog 컴포넌트 제작

- src/components/BackButton/BackButton.jsx
- src/components/BackButton/BackButton.module.css
feature/back_button-> develop
- 클릭 시 이전 페이지로 이동
- 색상 2가지 고려
Resolves #3
> feat: backButton 컴포넌트 제작

- src/pages/userInfoInput/components/SkipButton.jsx
- src/pages/userInfoInput/components/SkipButton.module.css
feature/userInfoInput_skip-> develop 
- 건너뛰기 버튼 클릭 시 지정 페이지로 이동 가능
- 색상 2가지 고려
Resolves #26
> feat: 유저정보입력 - 건너뛰기 버튼 컴포넌트 제작

- src/pages/userInfoInput/components/ProgressBar/ProgressBar.jsx
- src/pages/userInfoInput/components/ProgressBar/ProgressBar.module.css
feature/ProgressBar -> develop
- progress prop으로 진행도를 전달 받음
- progress prop은 정수 1~5로 제한
- progress가 변할 때 0.3초에 걸쳐 서서히 길어지도록 애니메이션 설정
- 모바일, desktop 스타일을 다르게 했는데, 위치는 페이지 레이아웃에서 조정하면 될 것 같습니다
Resolves #31
> feat: ProgressBar 컴포넌트 제작

- src/pages/myPage/components/InterestBadge/InterestBadge.jsx
- src/pages/myPage/components/InterestBadge/InterestBadge.module.css
feature/myPage_intersetBadge -> develop
- props에 배열로 관심사 최대 3개를 받음
- 관심사가 없을 경우 "관심사가 없습니다" 출력
Resolves #35
> feat: 마이페이지 - InterestBadge

- public/sprites.svg
- src/icons.js
- src/pages/seeReply/components/MusicReply/MusicReply.jsx
- src/pages/seeReply/components/MusicReply/MusicReply.module.css
feature/seeReply -> develop
- 앨범 커버, 앨범 타이틀, 노래 제목 정보 받아 출력
Resolves #37
> feat: MusicReply 컴포넌트 제작

- src/components/AuthInput/AuthInput.jsx
- src/components/AuthInput/AuthInput.module.css
feature/AuthInput -> develop
- 로그인, 회원가입 두 페이지에서 사용되므로 공용 컴포넌트로 만들었음
- username, password, passwordConfirm 세 가지 name (서버에 전달하기 좋게 name지정)
- text, password 두 가지 type
- width는 100%로 했음 (form의 width로 조절, max-width를 desktop 시안의 사이즈인 552로 설정함)
mobile
desktop
Resolve #52
> feat: AuthInput 컴포넌트 제작

- src/components/RadioInput/RadioInput.jsx
- src/components/RadioInput/RadioInput.module.css
- 3가지 스타일
feature/radio-> develop
- 3가지 스타일의 라디오 Input
- 클릭 시 색상 변경
Resolves #42
> feat: RadioInput 컴포넌트 제작

- src/pages/musicPage/components/PlayTime/PlayTime.jsx
- src/pages/musicPage/components/PlayTime/PlayTime.module.css
feature/music_PlayTime -> develop
- "00:00" 형식 포맷 함수 추가
- 2가지 색상의 스타일 추가
Resolves #67
> feat: music play time

- src/pages/musicPage/components/MusicButton/MusicButton.jsx
- src/pages/musicPage/components/MusicButton/MusicButton.module.css
feature/music_MusicButton-> develop
- 앨범 이미지, 음악 제목, 아티스트 props로 받아 출력
- button 형태로 제작
Resolves #71
> feat: MusicButton 컴포넌트 제작

- package.json
- pnpm-lock.yaml
- src/components/BackButton/BackButton.jsx
- src/components/ToasterProvider/ToasterProvider.module.css
- src/pages/signInPage/SignInPage.module.css
- src/pages/signInPage/index.jsx
feature/signInPage -> develop 
- 아이디, 비밀번호 입력 시 버튼 활성화
- 로그인 진행 시 로딩 스피너 추가
- Toaster를 통해 로그인 실패 알림
Resolves #99
> feat: signInPage 제작

- src/hooks/useFetch.js
- src/layouts/RootLayout/RootLayout.jsx
- src/pages/calendarPage/index.jsx
- src/pages/letterBoxPage/LetterBoxPage.module.css
- src/pages/letterBoxPage/index.jsx
- src/pages/pickUpBottlePage/PickUpBottlePage.module.css
- src/pages/pickUpBottlePage/index.jsx
- src/pages/pickUpBottlePage/pickUpBottlePage.module.css
- src/pages/viewDiaryPage/index.jsx
- src/pages/viewLetterpage/index.jsx
- useFetch 훅의 초기 상태를 loading으로 설정
- 변경에 따른 코드 수정
- RootLayout에서 fetchUerInfo() 제거
Resolve #123
> refactor: useFetch 훅 수정

- src/api/users.js
- src/pages/myPage/components/UserProfile/UserProfile.jsx
- src/pages/statisticsPage/components/AIReplyType/AIReplyType.jsx
- src/pages/statisticsPage/components/AIReplyType/AIReplyType.module.css
- src/pages/statisticsPage/components/AnalysisReport/AnalysisReport.jsx
- src/pages/statisticsPage/components/AnalysisReport/AnalysisReport.module.css
- src/pages/statisticsPage/components/EmotionPercentage/EmotionPercentage.jsx
- src/pages/statisticsPage/components/EmotionPercentage/EmotionPercentage.module.css
- src/pages/statisticsPage/components/ReplyFromPercentage/ReplyFromPercentage.jsx
- src/pages/statisticsPage/components/ReplyFromPercentage/ReplyFromPercentage.module.css
- src/pages/statisticsPage/index.jsx
- src/pages/statisticsPage/statisticsPage.module.css
faeture/statisticsPage -> develop
- 통계 Card 각각 컴포넌트 제작
- PC, Mobile UI 고려
Resolves #109
> feat: statisticsPage 제작

- package.json
- pnpm-lock.yaml
- src/api/gemini.js
- src/constants.js
- src/icons.js
- src/pages/selectReplyPage/components/ContentsRadioGroup/ContentsRadioGroup.jsx
- src/pages/selectReplyPage/index.jsx
- src/pages/viewDiaryPage/index.jsx
feature/gemini-> develop
- 구글 Gemini AI를 활용하여 사용자의 일기에 답장을 받을 수 있습니다.
Resolves #135
> feat: gemini를 활용한 답장 제작

- src/api/replies.js
- src/pages/calendarPage/index.jsx
- src/pages/signUpPage/index.jsx
- src/pages/statisticsPage/components/AIReplyType/AIReplyType.jsx
- src/pages/statisticsPage/components/EmotionPercentage/EmotionPercentage.jsx
- src/pages/statisticsPage/components/EmotionPercentage/EmotionPercentage.module.css
- src/pages/statisticsPage/components/ReplyFromPercentage/ReplyFromPercentage.jsx
- src/pages/statisticsPage/components/ReplyFromPercentage/ReplyFromPercentage.module.css
- src/pages/statisticsPage/index.jsx
- src/pages/userInfoInputPage/index.jsx
feature/statistics -> develop
- 통계 차트 계산을 할 데이터가 없을 경우 예외 처리 진행
- 회원가입 완료 후 이동되는 페이지 주소 변경
- 유저정보입력 페이지의 ProgressBar 값에 "6"이 들어가 제외
- 캘린더 페이지 유저 정보 연결
- AIReplyType, ReplyFromPercentage에서 잘 못 계산되던 답장 데이터 수정
Resolves #141
> refactor: statistics 계산 데이터 수정

- netlify.toml
- src/pages/calendarPage/CalendarModal/CalendarModal.jsx
- src/pages/homePage/components/SelectEmotionModal/SelectEmotionModal.jsx
- src/pages/userInfoInputPage/components/KeywordInput/KeywordInput.module.css
- src/pages/userInfoInputPage/components/KeywordList/KeywordList.module.css
feature/bugFix -> develop
- netlify 배포 문제 해결 (해결됐는지는 배포 해봐야 암)
- 모달창 관련
- SelectEmotionModal의 Plus버튼 위치 수정
- CalenderModal, SelectEmotionModal의 role 수정
- CalendarModal, SelectEmotionModal의 focus 수정
- role="dialog"를 overlay가 아닌 content 영역으로 이동
- 포커스트래핑을 위한 ref를 overlay가 아닌 content영역의 div로 이동
- 모달이 열릴 때, dialog 창이 focus되도록 수정
- 윈도우에서 keywordInput에서 글자가 삐져나가는 현상 수정
- grid로 고정된 영역을 차지하는게 아니라 flex로 설정해서 텍스트가 길어지면 input 길이가 늘어나도록 함
Resolves #149
> bugFix: 최종발표 때 발견한 오류들 수정

- src/components/ToasterProvider/ToasterProvider.jsx
- src/components/ToasterProvider/ToasterProvider.module.css
- src/stores/ToasterStore.js
feature/toast-> develop 
- 토스트 최대 출력 개수 3개로 제한
- type으로 default 추가 (하얀 색상)
Resolves #154
> feat: Toast 수정

- package.json
- pnpm-lock.yaml
- src/api/diaries.js
- src/api/replies.js
- src/main.jsx
- src/pages/calendarPage/index.jsx
- src/pages/homePage/components/Greeting/Greeting.module.css
- src/pages/homePage/index.jsx
- src/pages/letterBoxPage/index.jsx
- src/pages/pickUpBottlePage/components/BottleRadio/BottleRadio.module.css
- src/pages/pickUpBottlePage/index.jsx
- src/pages/selectReplyPage/components/ContentsRadioGroup/ContentsRadioGroup.jsx
- src/pages/selectReplyPage/components/ReplierRadioGroup/ReplierRadioGroup.jsx
- src/pages/settingsPage/SettingsPage.module.css
- src/pages/userInfoInputPage/index.jsx
- src/pages/writeDiaryPage/index.jsx
feature/conditionalRedirect -> develop
- settingsPage에서 전역 스타일 침범 수정
- homePage의 상단 메세지박스를 닫아도 모바일에서 그림자가 남아있어서 그림자 제거
- react-query 및 react-query-devtools 패키지 추가
- pickUpBottlePage, letterBoxPage, calendarPage의 포켓베이스 데이터를 react-query로 관리하도록 변경
(앱을 새로고침하기 전까지 서버에서 가져온 데이터를 가지고 있고, 서버의 데이터와 비교해서 변경된 사항이 없다면 이미 가지고 있는 데이터를 다시 요청하지 않고 사용)
- pickUpBottlePage에서 답장할 편지가 없거나, 오늘 이미 답장을 했다면 homePage로 redirect
- letterBoxPage에서 아직 받은 답장이 없다면 homePage로 redirect
- writeDiaryPage에서 오늘 이미 일기를 작성했다면 homePage로 redirect
> feat: react-query 사용 및 조건부 redirect / bugFix: 전역 스타일 침범 수정 및 homePage의 모바일 디자인 오류 수정

- src/pages/viewDiaryPage/components/BookReply/BookReply.jsx
- src/pages/viewDiaryPage/components/MusicReply/MusicReply.jsx
- src/pages/viewDiaryPage/components/VideoReply/VideoReply.jsx
- src/pages/viewDiaryPage/index.jsx
feature/Reply -> develop
- desktop 상태에 따라 두가지 사이즈로 넣었습니다
Resolves #164
> refactor: viewDiaryPage의 답장 컨텐츠 이미지를 아이콘으로 변경
